version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.24.4
    working_directory: ~/project

jobs:
  test:
    executor: go-executor
    steps:
      - checkout
      - run: go mod tidy
      - run: go test ./... -v

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Scaleway CLI
          command: |
            curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh
            scw version

      - run:
          name: Create Scaleway config file
          command: |
            mkdir -p /home/circleci/.config/scw
            cat \<<EOF > /home/circleci/.config/scw/config.yaml
access_key: $SCW_ACCESS_KEY
secret_key: $SCW_SECRET_KEY
default_region: $SCW_DEFAULT_REGION
default_project_id: $SCW_DEFAULT_PROJECT_ID
send_telemetry: false
EOF
      - run:
          name: Build and package function
          command: |
            zip -r function.zip handler.go go.mod go.sum
      - run:
          name: Deploy to Scaleway Functions
          command: |
            scw function deploy name=$SCW_FUNCTION_NAME \
              namespace-id=$SCW_NAMESPACE_ID \
              runtime=go124 \
              zip-file=function.zip

workflows:
  build-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
