version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.24.4
    working_directory: ~/project

jobs:
  test:
    executor: go-executor
    steps:
      - checkout
      - run: go mod tidy
      - run: go test ./... -v

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Scaleway CLI
          command: |
            curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh
            scw version
      - run:
          name: Authenticate with Scaleway
          command: |
            echo "ACCESS KEY: $SCW_ACCESS_KEY"
            echo "SECRET KEY: $SCW_SECRET_KEY"
            echo "REGION: $SCW_DEFAULT_REGION"
            echo "PROJECT ID: $SCW_DEFAULT_PROJECT_ID"
            echo "NAMESPACE ID: $SCW_NAMESPACE_ID"
            echo "FUNCTION NAME: $SCW_FUNCTION_NAME"

            scw config set access-key "$SCW_ACCESS_KEY"
            scw config set secret-key "$SCW_SECRET_KEY"
            scw config set default-region "$SCW_DEFAULT_REGION"
            scw config set default-project-id "$SCW_DEFAULT_PROJECT_ID"
      - run:
          name: Build and package function
          command: |
            zip -r function.zip handler.go go.mod go.sum
      - run:
          name: Deploy to Scaleway Functions
          command: |
            scw function deploy name=$SCW_FUNCTION_NAME \
              namespace-id=$SCW_NAMESPACE_ID \
              runtime=go124 \
              zip-file=function.zip

workflows:
  build-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
