version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.24.4
    working_directory: ~/project

jobs:
  test:
    executor: go-executor
    steps:
      - checkout
      - run: go mod tidy
      - run: go test ./... -v

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Scaleway CLI
          command: |
            curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh
            scw version

      - run:
          name: Create Scaleway config file
          command: |
            mkdir -p /home/circleci/.config/scw
            echo "access_key: $SCW_ACCESS_KEY" | tee /home/circleci/.config/scw/config.yaml > /dev/null
            echo "secret_key: $SCW_SECRET_KEY" >> /home/circleci/.config/scw/config.yaml
            echo "default_region: $SCW_DEFAULT_REGION" >> /home/circleci/.config/scw/config.yaml
            echo "default_project_id: $SCW_DEFAULT_PROJECT_ID" >> /home/circleci/.config/scw/config.yaml
            echo "default_organization_id: $SCW_DEFAULT_ORGANIZATION_ID" >> /home/circleci/.config/scw/config.yaml
            echo "send_telemetry: false" >> /home/circleci/.config/scw/config.yaml

      - run:
          name: Build and package function
          command: |
            zip -r function.zip handler.go go.mod go.sum
      - run:
          name: Deploy to Scaleway Functions
          command: |
            scw function deploy name=$SCW_FUNCTION_NAME \
              namespace-id=$SCW_NAMESPACE_ID \
              runtime=go124 \
              zip-file=function.zip

workflows:
  build-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
